# -*- coding: utf-8 -*-
"""Breast_cancer_Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1airpQgF9nP50vXtp2GwbICc3amFB0uLe

**Breast Cancer Testing Model**
"""

import numpy as np
import pandas as pd
import sklearn.datasets 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""Data Collection and Processing"""

#Loading Data from Sklearn
breast_cancer_dataset = sklearn.datasets.load_breast_cancer()

print(breast_cancer_dataset)

#Loading data to pandas data frame
data_frame = pd.DataFrame(breast_cancer_dataset.data, columns = breast_cancer_dataset.feature_names)

#printing first 5 rows of the data
data_frame.head()

#adding the 'target' columns to the data frame
data_frame['label'] = breast_cancer_dataset.target

data_frame.tail()

#number of row and coloums in data frame
data_frame.shape

#getting some information from data 
data_frame.info()

#checking for missing values
data_frame.isnull().sum()

#statical measure about the data set
data_frame.describe()

#checking the the distrabution of target variable 
data_frame['label'].value_counts()

"""1 --> Benign
2 --> Malignant
"""

data_frame.groupby('label').mean()

#Saprating featue and target
X = data_frame.drop(columns='label', axis=1)
Y = data_frame['label']

print(X)
print(Y)

"""Splitting the data into traning data & Test Data"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

print(X.shape, X_test.shape, X_train.shape)

"""Model Tranig

Logistic regrassion
"""

model = LogisticRegression()

#Traning The Logistic Regrassion model using traning data
model.fit(X_train, Y_train)

"""Model Evalution

Acccuracy Score
"""

#Accuracy on train Data 
X_train_predictin = model.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_predictin)

print('Accuracy on traning data =', training_data_accuracy)

#Accuracy on test Data 
X_test_predictin = model.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_predictin)

print('Accuracy on test data =', test_data_accuracy)

"""Building a Cancer Pridective System"""

input_data = (12.86,18,83.19,506.3,0.09934,0.09546,0.03889,0.02315,0.1718,0.05997,0.2655,1.095,1.778,20.35,0.005293,0.01661,0.02071,0.008179,0.01748,0.002848,14.24,24.82,91.88,622.1,0.1289,0.2141,0.1731,0.07926,0.2779,0.07918)
#change input data to numpy array 
input_data_as_numpy_array = np.asarray(input_data)

#reshape the numpy array as we are predicting for one datapoint
input_data_as_numpy_array = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_as_numpy_array)
print(prediction)

if (prediction[0] == 0):
  print("The Breast Cancer is Malignant")

else:
  print("The Breast Cancer is Benign")

